### PR TITLE
highlight selected region

### PR DESCRIPTION
**Pull request by thenaterhood**
Implements #186

### CODE REVIEW

**Comment by mark2185** [comment]
I'm guessing this may have broken the tool for me (at least it doesn't work properly on 3.5.1, but it does on 3.5.0 and my guess is that it's this feature) in the sense that selected region is grayed out instead of "highlighted" which wouldn't be a problem per se, but the entire screen is greyed out until I start selecting something.

How can I help you fix it?

**Comment by thenaterhood** [comment]
That sounds like it's working correctly, when you choose to take a selection then it preselects the entire screen and you can click and drag. There's no change to that behavior in 3.5.1, just the color used for highlighting/greying the selected area.

**Comment by mark2185** [comment]
But it's not just _highlighted_, it's grey with **full** opacity, I don't see where I want to click until I click somewhere and by then it's too late if I miss.

**Comment by thenaterhood** [comment]
I'd have to know more, I can't reproduce that on X11 or Wayland. In my testing the region selection is still transparent.

**Comment by mark2185** [comment]
Sure, what info can I provide?

I'm running i3 with no composer so I don't have transparency in general.

**Comment by thenaterhood** [comment]
If you want to experiment, these are the selection calls that gscreenshot uses

Slop (generally for X11): `slop --nodecorations=0 -l -c 0.8,0.8,0.8,0.6` (the last number, 0.6, is the transparency)
Slurp (generally for Wayland): `slurp -b '#00000011' -s '#cccccc55' -c '#808080FF'` (the middle number ending in 55 is the selection color - the "55" is the transparency level)

I suspect if you're not using a compositor you'll have limited success with transparency but if you adjust those and find a transparency level that works let me know. It's possible that without a compositor the opacity level is getting rounded up or down so before it was rounded to something like 0 making the highlight invisible, but now that it's higher it's getting rounded up to 100%.

**Comment by mark2185** [comment]
> Slop (generally for X11): slop --nodecorations=0 -l -c 0.8,0.8,0.8,0.6 (the last number, 0.6, is the transparency)

Yeah, any and all values for the transparency result in an opaque patch on the screen.

I think I'll stick to `3.5.0` for the time being since it seems to be working fine, and I don't really feel like digging deeper. Thanks, though!

**Comment by thenaterhood** [comment]
The commands from 3.5.0 are:

Slop (X11) : `slop --nodecorations=0`
Slurp (Wayland): `slurp -b '#00000011' -s '#00000011' -c '#808080FF'`

I assume you're probably on X11 (the About dialog will tell you if gscreenshot is using slop or slurp). I wonder if the slop color setting gets ignored without compositing because I actually can also get a 100% opaque selection highlight if I leave off the color (-c) option.

**Pull request merged**
