### PR TITLE
Output file name

### PR DESCRIPTION
**Pull request by pavroo**
There is an empty output file name with no even an extension when trying save a screenshot file.
I suggest / request to change the empty name to a default name with a proper extension, for example:
screenshot.png
or
screenshot-YYYYMMDD-HHMM.png ( screenshot-%Y-%m-%d-%s.png )

The name should still be editable via an user.

### CODE REVIEW

**Comment by thenaterhood** [comment]
I think you wanted to open an issue instead of a pull request :). I've actually been looking into the best way to go about this on and off but I haven't found a good solution to it just yet.

**Comment by pavroo** [comment]
Oppsss... I think so.

**Comment by thenaterhood** [comment]
No worries, I knew what you meant :). I'll see if I can get this in the next release, I probably just need to poke around a little for the right method call.

**Comment by thenaterhood** [comment]
Resolved: https://github.com/thenaterhood/gscreenshot/releases/tag/v2.4.0

**Pull request closed without merging**
