### PR TITLE
GUI slight adjustents to control alignment

### PR DESCRIPTION
**Pull request by zv0n**
The gui didn't look right on my system, delay counter was too narrow, so the number couldn't be seen and the "Save as" button had the down arrow a few pixels to the right which looked strange. I edited it and now it looks ok on my machine, hope it can be merged.

### CODE REVIEW

**Comment by thenaterhood** [comment]
Thanks for the pull request! I've been fighting with the alignment for a while, and it's hard to test because I don't have many screen resolutions available to me.

Unfortunately, this seems to make it worse for me :'(. Take a look:
image

**Comment by zv0n** [comment]
Is it any better now? I tried removing the scrollwindow, so theoretically it should force the window size to be as large as necessary. I've also replaced buttonboxes with regular boxes and that might help somehow ¯\_(ツ)_/¯

**Comment by zv0n** [comment]
Nevermind, I was only testing it out in Glade and there it worked fine, but when I tried it with gscreenshot the image behaves...strangely. I'll try to fix that :D

**Comment by zv0n** [comment]
I think it should be fine now, did another edit of the glade file and changed gtk.py so the image resizing would work properly with the changes

**Comment by thenaterhood** [comment]
Nice! That's better, but still not quiiiite right. Moving in the right direction, and I like the button reliefs that are there now.

It looks a little disproportionate at its default start size (although, no scrollbars and everything is visible!)
image

Maximized, it flies apart a little and once it's maximized it's "stuck" that way. Might have to do with the preview size not getting adjusted. One of the benefits of scaling the preview by multiplying rather than subtracting a static number is that it should scale better between different resolutions. Something to be cautious of too is how the preview gets scaled when there are multiple monitors.

image

**Comment by zv0n** [comment]
Hi, I completely forgot about this PR :D
I tried changing the scaling back to multiplying, I've also changed it so it only scales once the window has stopped growing (which should hopefully lead to fewer computations => faster program). I also added a box around the controls, so it should be centered now even in fullscreen mode.

**Comment by zv0n** [comment]
@thenaterhood What do you think? Is it alright now?

**Comment by thenaterhood** [comment]
Welcome back!

Moving in the right direction :). The controls are centered when it's maximized now, solid :+1: on that. There are still two quirks though:

- The window gets stuck maximized or "snapped". You can manually resize it back down, but trying to unmaximize/unsnap to the previous size doesn't work. There might be some state tracking that's a problem - when I ran into this, I ended up storing a flag as to whether the window was maximized and its previous size so I could restore it. Might be something like that.
- The default size of the window (or perhaps just the controls or preview) is a little off on my screen resolution. It makes the window a little bigger and the controls further apart than they need to be:
image

**Comment by zv0n** [comment]
@thenaterhood I think I fixed the issues, I changed the preview calculation to use size of the main box container instead of the window size, so that should hopefully prevent the window getting stuck when maximized, I tried it in Gnome and had no problems. I also removed homogeneity from the control grid, so the buttons shouldn't be as spaced out. The only problem I've encountered is that resizing takes a little while, but that's to be expected I think since the image size is recalculated with every resize :D

**Comment by zv0n** [comment]
I tried making the window resize a bit snappier, I think I succeeded, but I might just be telling myself that after staring at it for so long :D

**Comment by thenaterhood** [comment]
I feel that, it's hard to tell when it comes to little speed things like that. I think it does feel a little snappier.

I think you've made the maximization thing better, but it's still a problem. I can't quite figure out what's going wrong with it, because it does work sometimes, but other times there is still a problem with it.

Also, it's possible to resize the window until the preview disappears, probably a minimum size missing somewhere.

**Comment by zv0n** [comment]
From what I've tested (GNOME and bspwm), the maximization works, so can't really fix that since it's working for me. The minimum size - what do you think is a sensible minimum?

**Comment by thenaterhood** [comment]
Interesting! I'm on XFCE - maybe there's some extra state somewhere that matters in the XFCE world. I think there are two things happening - it doesn't fully restore its pre-maximized size, and the window is still in the maximized state as far as the window manager (XFWM) is concerned so it doesn't toggle back to unmaximized. But, if that's not the environment you're on, then I can't fault you for not testing there :)

Size-wise let's use the original size of the window as the minimum. One less thing to remember.

**Comment by zv0n** [comment]
Hi,
I've rebased to your latest commit and added min window size, so I hope it's all behaving as it should and can be merged :D

**Comment by zv0n** [comment]
@thenaterhood so, what do you think? :D

**Comment by thenaterhood** [comment]
I think it all looks good! Thanks for getting that fixed, I appreciate your help.

**Pull request merged**
